#include <stdio.h>
#include <stdlib.h>

#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/adc.h"
#include "hardware/clocks.h"
#include "ws2812.pio.h"

#define IS_RGBW true        // Will use RGBW format
#define NUM_PIXELS 1        // There is 1 WS2812 device in the chain
#define WS2812_PIN 28       // The GPIO pin that the WS2812 connected to

/**
 * @brief Wrapper function used to call the underlying PIO
 *        function that pushes the 32-bit RGB colour value
 *        out to the LED serially using the PIO0 block. The
 *        function does not return until all of the data has
 *        been written out.
 * 
 * @param pixel_grb The 32-bit colour value generated by urgb_u32()
 */

static inline void put_pixel(uint32_t pixel_grb) {
    pio_sm_put_blocking(pio0, 0, pixel_grb << 8u);
}

/**
 * @brief Function to generate an unsigned 32-bit composit GRB
 *        value by combining the individual 8-bit paramaters for
 *        red, green and blue together in the right order.
 * 
 * @param r     The 8-bit intensity value for the red component
 * @param g     The 8-bit intensity value for the green component
 * @param b     The 8-bit intensity value for the blue component
 * @return uint32_t Returns the resulting composit 32-bit RGB value
 */

static inline uint32_t urgb_u32(uint8_t r, uint8_t g, uint8_t b) {
    return  ((uint32_t) (r) << 8)  |
            ((uint32_t) (g) << 16) |
            (uint32_t) (b);
}

void std_clr_update(float t_read)
{
    if (t_read > 70)
        put_pixel(urgb_u32(0x7F, 0x00, 0x00));
    else if (t_read > 30)
        put_pixel(urgb_u32(0x7F, 0x6B, 0x00));
    else
        put_pixel(urgb_u32(0x00, 0x7F, 0x00));
}

// uint16_t asm_adc_read()
void std_adc_func_read()
{
    uint16_t adc_raw = adc_read();
    const float c_read = 3.3f / (1 << 12);
    float v_read = adc_raw * c_read;
    float temp = 27 - (v_read - 0.706) / 0.001721;

    printf("Raw Adc reading : %x\n", adc_raw);
    printf("Float Converted readings  : %f\n", v_read);
    printf("Temperature reading : %f\n", temp);

    std_clr_update(temp);
}

/**
 * @brief LAB #09 - TEMPLATE
 *        Main entry point for the code - calls the main assembly
 *        function where the body of the code is implemented.
 * 
 * @return int      Returns exit-status zero on completion.
 */

void std_init()
{
    // Library function calling 
    adc_init();
    adc_set_temp_sensor_enabled(true);
}

void std_adc_func(uint input_adc)
{
    // Library function calling  
    adc_select_input(input_adc);
}

int main() {

    // Initialise all STDIO as we will be using the GPIOs
    stdio_init_all();

     // Initialise the PIO interface with the WS2812 code
    PIO pio = pio0;
    uint offset = pio_add_program(pio, &ws2812_program);
    ws2812_program_init(pio, 0, offset, WS2812_PIN, 800000, IS_RGBW);
    // Jump into the main assembly code subroutine.
    main_asm();


    // Returning zero indicates everything went okay.
    return 0;
}